## TFM. Paso 1 -  Concatenar Datasets

Ya que tenemos todos los datasets en archivos excels diferentes, lo primero que haremos será unirlos en un mismo dataframe. Para ello, utilizaremos una función que vaya recorriendo el path donde están guardados todos los archivos y uniéndolos con un concat.

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = r"C:/Users/carlos.guisado/Documents/Thomson/Uipath/Descargas/Data/"
archivo = os.listdir(r"C:\Users\carlos.guisado\Documents\Thomson\Uipath\Descargas\Data")

In [4]:
print("Contamos con " + str(len(archivo)) + " datasets, que equivalen a los datos financieros de " + str(len(archivo)) + " empresas que cotizan en la bolsa americana.")

Contamos con 1166 datasets, que equivalen a los datos financieros de 1166 empresas que cotizan en la bolsa americana.

In [42]:
#Abrimos el primer excel de todos para comprobar que se ha cargado correctamente.
#Archivo Excel ajuntado en Github - df.xlsx
df = pd.read_excel(r"C:\Users\carlos.guisado\Documents\Thomson\Uipath\Descargas\Data\A.xlsx", sheet_name = "FinancialData")
df.head()

,Company Name,Country,TRBC Industry Group,Reporting Unit,Field Name,Mkt Cap Var,Market Capitalization,Tot Rev from Biz Activ,Gross Profit - Ind/Prop - Tot,Op Profit Bef Non-Recur Inc/(Expn),...,PE Growth Ratio,"PE Growth Ratio, 5 Yr Avg",Enterprise Value To Tot Rev,"Enterprise Value To Tot Rev, 5 Yr Avg",Enterprise Value To EBITDA,"Enterprise Value To EBITDA, 5 Yr Avg",Enterprise Value To Net Cash Flow From Op,"Enterprise Value To Net Cash Flow From Op, 5 Yr Avg",Enterprise Value To FOCF,"Enterprise Value To FOCF, 5 Yr Avg"
0,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2019,NaN,23442.18,5163,2813,997,...,0.86,0.71,4.74,4.03,19.80,17.87,23.96,21.35,37.13,33.93
1,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2018,0.135045,20653.08,4914,2684,933,...,0.89,0.95,4.11,3.93,17.65,17.93,18.59,21.35,28.11,35.86
2,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2017,-0.056677,21893.96,4472,2398,818,...,0.66,-4.32,4.75,3.96,20.57,18.65,23.88,20.18,39.10,33.29
3,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2016,0.549089,14133.44,4202,2200,656,...,4.19,-1.89,3.27,3.18,15.23,15.30,17.34,16.65,27.28,25.72
4,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2015,0.129429,12513.79,4038,2023,568,...,0.32,-2.50,3.01,2.79,14.80,13.63,23.77,14.59,43.31,20.79

In [43]:
#Añadimos, utilizando un 'concat', los datos de las demás empresas que queremos analizar, con el 
#objetivo de crear un dataset con todas las empresas y datos financieros.
for i in range (1,len(archivo)):
    file = path + archivo[i]
    temp_data = pd.read_excel(file, sheet_name = "FinancialData")
    df = pd.concat([df, temp_data], axis = 0, ignore_index = True, verify_integrity = True)
df = df.dropna(axis = 1, how = 'all')
df

,Company Name,Country,TRBC Industry Group,Reporting Unit,Field Name,Mkt Cap Var,Market Capitalization,Tot Rev from Biz Activ,Gross Profit - Ind/Prop - Tot,Op Profit Bef Non-Recur Inc/(Expn),...,"Enterprise Value To Net Cash Flow From Op, 5 Yr Avg.1",Enterprise Value To FOCF.1,"Enterprise Value To FOCF, 5 Yr Avg.1","Div Yld - Com Stock - Issue, 3 Yr Avg.2","Div Yld - Com Stock - Issue, 3 Yr Avg.3",Non-GAAP Adj EBITDA.1,Non-GAAP Free Cash Flow.1,Net Stable Funding Ratio - Basel 3 - %,"Div Yld - Com Stock - Issue, TTM.4","Div Yld - Com Stock - Issue, TTM.5"
0,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2019,NaN,23442.18,5163.0,2813.0,997.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2018,0.135045,20653.08,4914.0,2684.0,933.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2017,-0.056677,21893.96,4472.0,2398.0,818.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2016,0.549089,14133.44,4202.0,2200.0,656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Agilent Technologies Inc (A),United States of America,Healthcare Equipment & Supplies,Millions,31-10-2015,0.129429,12513.79,4038.0,2023.0,568.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14007,Zoetis Inc (ZTS),United States of America,Pharmaceuticals,Millions,31-12-2014,0.106079,21572.01,4785.0,3040.0,998.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14008,Zoetis Inc (ZTS),United States of America,Pharmaceuticals,Millions,31-12-2013,0.319775,16345.22,4561.0,2856.0,849.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14009,Zoetis Inc (ZTS),United States of America,Pharmaceuticals,Millions,31-12-2012,NaN,NaN,8672.0,7087.0,5231.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14010,Zoetis Inc (ZTS),United States of America,Pharmaceuticals,Millions,31-12-2011,NaN,NaN,8466.0,6777.0,4913.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14011,Zoetis Inc (ZTS),United States of America,Pharmaceuticals,Millions,31-12-2010,NaN,NaN,7164.0,5692.0,3908.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
print("Tenemos un dataset compuesto por " + str(len(archivo)) + " empresas, con un shape = " + str(df.shape))
print("Esto se debe a que cada empresa, como hemos visto anteriormente al abrir el primero de los archivos, está compuesta por un historial variable de entre 1-10 años.")
print("Dependiendo de la industria, disponemos de unos datos financieros o de otros, por lo que el siguiente paso será la división por industria.")

Tenemos un dataset compuesto por 1166 empresas, con un shape = (14012, 464)
Esto se debe a que cada empresa, como hemos visto anteriormente al abrir el primero de los archivos, está compuesta por un historial variable de entre 1-10 años.
Dependiendo de la industria, disponemos de unos datos financieros o de otros, por lo que el siguiente paso será la división por industria.

In [44]:
df.to_excel('df.xlsx', header=True, index=False)